app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_comment_api:
    type: rest
    # resource: "@FOSCommentBundle/Resources/config/routing.yml"
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }