# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   app.form.registration:
        class: AppBundle\Form\RegistrationType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: app_user_registration }
            
   app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }            

   fos_user.doctrine_registry:
        alias: doctrine   
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
