<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository {
  //http://guidella.free.fr/General/symfony2DoctrineQueryLanguage.html
  public function lesQuestions($classroom, $user) {
    $em=  $this->getEntityManager();
    $query =  $em->createQuery('SELECT q FROM AppBundle:Question q WHERE q.classroom = :c AND (q.datepub is not null OR q.designer = :u)');
    $query->setParameter('c', $classroom);
    $query->setParameter('u', $user);
    return $query->getResult();
  }
  
  /**
   * 
   * @param Classroom $classroom
   * @param User $user
   * @param int $scope
   * @return array of instances of Question
   */
  public function questionsParTheme($classroom, $user, $scope) {
    $em=  $this->getEntityManager();
    $query =  $em->createQuery('SELECT q FROM AppBundle:Question q WHERE q.classroom = :c AND (q.datepub is not null OR q.designer = :u) AND q.scope = :s');
    $query->setParameter('c', $classroom);
    $query->setParameter('u', $user);
    $query->setParameter('s', $scope);
    return $query->getResult();
  }
}
