<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository {

  /** Get the average rating of a question.
    * 
    * @param type $question
    * @return type float
    */
  function getAvgRating($question) {
    $em = $this->getEntityManager(); 
    $query = $em->createQuery('SELECT AVG(r.value) FROM AppBundle:Rating r WHERE r.question=:question');
    $query->setParameter('question', $question);
    return $query->getSingleScalarResult();
  }

}
